// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: pool/pool_with_map_reuse.proto

package pool

import (
	_ "github.com/planetscale/vtprotobuf/vtproto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MapReuseTest1_TEST int32

const (
	MapReuseTest1_test1 MapReuseTest1_TEST = 0
	MapReuseTest1_test2 MapReuseTest1_TEST = 1
)

// Enum value maps for MapReuseTest1_TEST.
var (
	MapReuseTest1_TEST_name = map[int32]string{
		0: "test1",
		1: "test2",
	}
	MapReuseTest1_TEST_value = map[string]int32{
		"test1": 0,
		"test2": 1,
	}
)

func (x MapReuseTest1_TEST) Enum() *MapReuseTest1_TEST {
	p := new(MapReuseTest1_TEST)
	*p = x
	return p
}

func (x MapReuseTest1_TEST) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MapReuseTest1_TEST) Descriptor() protoreflect.EnumDescriptor {
	return file_pool_pool_with_map_reuse_proto_enumTypes[0].Descriptor()
}

func (MapReuseTest1_TEST) Type() protoreflect.EnumType {
	return &file_pool_pool_with_map_reuse_proto_enumTypes[0]
}

func (x MapReuseTest1_TEST) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MapReuseTest1_TEST.Descriptor instead.
func (MapReuseTest1_TEST) EnumDescriptor() ([]byte, []int) {
	return file_pool_pool_with_map_reuse_proto_rawDescGZIP(), []int{0, 0}
}

type MapReuseTest1 struct {
	state           protoimpl.MessageState        `protogen:"open.v1"`
	IntToStringMap  map[int32]string              `protobuf:"bytes,1,rep,name=intToStringMap,proto3" json:"intToStringMap,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	StringToEnumMap map[string]MapReuseTest1_TEST `protobuf:"bytes,2,rep,name=stringToEnumMap,proto3" json:"stringToEnumMap,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value,enum=MapReuseTest1_TEST"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *MapReuseTest1) Reset() {
	*x = MapReuseTest1{}
	mi := &file_pool_pool_with_map_reuse_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MapReuseTest1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MapReuseTest1) ProtoMessage() {}

func (x *MapReuseTest1) ProtoReflect() protoreflect.Message {
	mi := &file_pool_pool_with_map_reuse_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MapReuseTest1.ProtoReflect.Descriptor instead.
func (*MapReuseTest1) Descriptor() ([]byte, []int) {
	return file_pool_pool_with_map_reuse_proto_rawDescGZIP(), []int{0}
}

func (x *MapReuseTest1) GetIntToStringMap() map[int32]string {
	if x != nil {
		return x.IntToStringMap
	}
	return nil
}

func (x *MapReuseTest1) GetStringToEnumMap() map[string]MapReuseTest1_TEST {
	if x != nil {
		return x.StringToEnumMap
	}
	return nil
}

type TestObjWithoutPool struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Age           uint64                 `protobuf:"varint,2,opt,name=age,proto3" json:"age,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TestObjWithoutPool) Reset() {
	*x = TestObjWithoutPool{}
	mi := &file_pool_pool_with_map_reuse_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestObjWithoutPool) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestObjWithoutPool) ProtoMessage() {}

func (x *TestObjWithoutPool) ProtoReflect() protoreflect.Message {
	mi := &file_pool_pool_with_map_reuse_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestObjWithoutPool.ProtoReflect.Descriptor instead.
func (*TestObjWithoutPool) Descriptor() ([]byte, []int) {
	return file_pool_pool_with_map_reuse_proto_rawDescGZIP(), []int{1}
}

func (x *TestObjWithoutPool) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TestObjWithoutPool) GetAge() uint64 {
	if x != nil {
		return x.Age
	}
	return 0
}

type MapReuseTest2 struct {
	state                      protoimpl.MessageState        `protogen:"open.v1"`
	IntToMapReuseTest1Map      map[int32]*MapReuseTest1      `protobuf:"bytes,1,rep,name=intToMapReuseTest1Map,proto3" json:"intToMapReuseTest1Map,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	IntToTestObjWithoutPoolMap map[int32]*TestObjWithoutPool `protobuf:"bytes,2,rep,name=intToTestObjWithoutPoolMap,proto3" json:"intToTestObjWithoutPoolMap,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Count                      uint32                        `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields              protoimpl.UnknownFields
	sizeCache                  protoimpl.SizeCache
}

func (x *MapReuseTest2) Reset() {
	*x = MapReuseTest2{}
	mi := &file_pool_pool_with_map_reuse_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MapReuseTest2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MapReuseTest2) ProtoMessage() {}

func (x *MapReuseTest2) ProtoReflect() protoreflect.Message {
	mi := &file_pool_pool_with_map_reuse_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MapReuseTest2.ProtoReflect.Descriptor instead.
func (*MapReuseTest2) Descriptor() ([]byte, []int) {
	return file_pool_pool_with_map_reuse_proto_rawDescGZIP(), []int{2}
}

func (x *MapReuseTest2) GetIntToMapReuseTest1Map() map[int32]*MapReuseTest1 {
	if x != nil {
		return x.IntToMapReuseTest1Map
	}
	return nil
}

func (x *MapReuseTest2) GetIntToTestObjWithoutPoolMap() map[int32]*TestObjWithoutPool {
	if x != nil {
		return x.IntToTestObjWithoutPoolMap
	}
	return nil
}

func (x *MapReuseTest2) GetCount() uint32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type MapReuseTest3 struct {
	state                protoimpl.MessageState            `protogen:"open.v1"`
	StringToTimestampMap map[string]*timestamppb.Timestamp `protobuf:"bytes,1,rep,name=stringToTimestampMap,proto3" json:"stringToTimestampMap,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *MapReuseTest3) Reset() {
	*x = MapReuseTest3{}
	mi := &file_pool_pool_with_map_reuse_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MapReuseTest3) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MapReuseTest3) ProtoMessage() {}

func (x *MapReuseTest3) ProtoReflect() protoreflect.Message {
	mi := &file_pool_pool_with_map_reuse_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MapReuseTest3.ProtoReflect.Descriptor instead.
func (*MapReuseTest3) Descriptor() ([]byte, []int) {
	return file_pool_pool_with_map_reuse_proto_rawDescGZIP(), []int{3}
}

func (x *MapReuseTest3) GetStringToTimestampMap() map[string]*timestamppb.Timestamp {
	if x != nil {
		return x.StringToTimestampMap
	}
	return nil
}

var File_pool_pool_with_map_reuse_proto protoreflect.FileDescriptor

const file_pool_pool_with_map_reuse_proto_rawDesc = "" +
	"\n" +
	"\x1epool/pool_with_map_reuse.proto\x1a3github.com/planetscale/vtprotobuf/vtproto/ext.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xea\x02\n" +
	"\rMapReuseTest1\x12J\n" +
	"\x0eintToStringMap\x18\x01 \x03(\v2\".MapReuseTest1.IntToStringMapEntryR\x0eintToStringMap\x12M\n" +
	"\x0fstringToEnumMap\x18\x02 \x03(\v2#.MapReuseTest1.StringToEnumMapEntryR\x0fstringToEnumMap\x1aA\n" +
	"\x13IntToStringMapEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x05R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1aW\n" +
	"\x14StringToEnumMapEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12)\n" +
	"\x05value\x18\x02 \x01(\x0e2\x13.MapReuseTest1.TESTR\x05value:\x028\x01\"\x1c\n" +
	"\x04TEST\x12\t\n" +
	"\x05test1\x10\x00\x12\t\n" +
	"\x05test2\x10\x01:\x04\xa8\xa6\x1f\x01\":\n" +
	"\x12TestObjWithoutPool\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x10\n" +
	"\x03age\x18\x02 \x01(\x04R\x03age\"\xba\x03\n" +
	"\rMapReuseTest2\x12_\n" +
	"\x15intToMapReuseTest1Map\x18\x01 \x03(\v2).MapReuseTest2.IntToMapReuseTest1MapEntryR\x15intToMapReuseTest1Map\x12n\n" +
	"\x1aintToTestObjWithoutPoolMap\x18\x02 \x03(\v2..MapReuseTest2.IntToTestObjWithoutPoolMapEntryR\x1aintToTestObjWithoutPoolMap\x12\x14\n" +
	"\x05count\x18\x03 \x01(\rR\x05count\x1aX\n" +
	"\x1aIntToMapReuseTest1MapEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x05R\x03key\x12$\n" +
	"\x05value\x18\x02 \x01(\v2\x0e.MapReuseTest1R\x05value:\x028\x01\x1ab\n" +
	"\x1fIntToTestObjWithoutPoolMapEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x05R\x03key\x12)\n" +
	"\x05value\x18\x02 \x01(\v2\x13.TestObjWithoutPoolR\x05value:\x028\x01:\x04\xa8\xa6\x1f\x01\"\xd8\x01\n" +
	"\rMapReuseTest3\x12\\\n" +
	"\x14stringToTimestampMap\x18\x01 \x03(\v2(.MapReuseTest3.StringToTimestampMapEntryR\x14stringToTimestampMap\x1ac\n" +
	"\x19StringToTimestampMapEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x120\n" +
	"\x05value\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x05value:\x028\x01:\x04\xa8\xa6\x1f\x01B\x10Z\x0etestproto/poolb\x06proto3"

var (
	file_pool_pool_with_map_reuse_proto_rawDescOnce sync.Once
	file_pool_pool_with_map_reuse_proto_rawDescData []byte
)

func file_pool_pool_with_map_reuse_proto_rawDescGZIP() []byte {
	file_pool_pool_with_map_reuse_proto_rawDescOnce.Do(func() {
		file_pool_pool_with_map_reuse_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pool_pool_with_map_reuse_proto_rawDesc), len(file_pool_pool_with_map_reuse_proto_rawDesc)))
	})
	return file_pool_pool_with_map_reuse_proto_rawDescData
}

var file_pool_pool_with_map_reuse_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_pool_pool_with_map_reuse_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_pool_pool_with_map_reuse_proto_goTypes = []any{
	(MapReuseTest1_TEST)(0),       // 0: MapReuseTest1.TEST
	(*MapReuseTest1)(nil),         // 1: MapReuseTest1
	(*TestObjWithoutPool)(nil),    // 2: TestObjWithoutPool
	(*MapReuseTest2)(nil),         // 3: MapReuseTest2
	(*MapReuseTest3)(nil),         // 4: MapReuseTest3
	nil,                           // 5: MapReuseTest1.IntToStringMapEntry
	nil,                           // 6: MapReuseTest1.StringToEnumMapEntry
	nil,                           // 7: MapReuseTest2.IntToMapReuseTest1MapEntry
	nil,                           // 8: MapReuseTest2.IntToTestObjWithoutPoolMapEntry
	nil,                           // 9: MapReuseTest3.StringToTimestampMapEntry
	(*timestamppb.Timestamp)(nil), // 10: google.protobuf.Timestamp
}
var file_pool_pool_with_map_reuse_proto_depIdxs = []int32{
	5,  // 0: MapReuseTest1.intToStringMap:type_name -> MapReuseTest1.IntToStringMapEntry
	6,  // 1: MapReuseTest1.stringToEnumMap:type_name -> MapReuseTest1.StringToEnumMapEntry
	7,  // 2: MapReuseTest2.intToMapReuseTest1Map:type_name -> MapReuseTest2.IntToMapReuseTest1MapEntry
	8,  // 3: MapReuseTest2.intToTestObjWithoutPoolMap:type_name -> MapReuseTest2.IntToTestObjWithoutPoolMapEntry
	9,  // 4: MapReuseTest3.stringToTimestampMap:type_name -> MapReuseTest3.StringToTimestampMapEntry
	0,  // 5: MapReuseTest1.StringToEnumMapEntry.value:type_name -> MapReuseTest1.TEST
	1,  // 6: MapReuseTest2.IntToMapReuseTest1MapEntry.value:type_name -> MapReuseTest1
	2,  // 7: MapReuseTest2.IntToTestObjWithoutPoolMapEntry.value:type_name -> TestObjWithoutPool
	10, // 8: MapReuseTest3.StringToTimestampMapEntry.value:type_name -> google.protobuf.Timestamp
	9,  // [9:9] is the sub-list for method output_type
	9,  // [9:9] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_pool_pool_with_map_reuse_proto_init() }
func file_pool_pool_with_map_reuse_proto_init() {
	if File_pool_pool_with_map_reuse_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pool_pool_with_map_reuse_proto_rawDesc), len(file_pool_pool_with_map_reuse_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pool_pool_with_map_reuse_proto_goTypes,
		DependencyIndexes: file_pool_pool_with_map_reuse_proto_depIdxs,
		EnumInfos:         file_pool_pool_with_map_reuse_proto_enumTypes,
		MessageInfos:      file_pool_pool_with_map_reuse_proto_msgTypes,
	}.Build()
	File_pool_pool_with_map_reuse_proto = out.File
	file_pool_pool_with_map_reuse_proto_goTypes = nil
	file_pool_pool_with_map_reuse_proto_depIdxs = nil
}
