// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: pool/wkt_pool.proto

package pool

import (
	_ "github.com/planetscale/vtprotobuf/vtproto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WKTNestedPool struct {
	state protoimpl.MessageState   `protogen:"open.v1"`
	Ts    *timestamppb.Timestamp   `protobuf:"bytes,1,opt,name=ts,proto3" json:"ts,omitempty"`
	St    *structpb.Struct         `protobuf:"bytes,2,opt,name=st,proto3" json:"st,omitempty"`
	Tss   []*timestamppb.Timestamp `protobuf:"bytes,3,rep,name=tss,proto3" json:"tss,omitempty"`
	Sts   []*structpb.Struct       `protobuf:"bytes,4,rep,name=sts,proto3" json:"sts,omitempty"`
	// Types that are valid to be assigned to Choice:
	//
	//	*WKTNestedPool_ChoiceTs
	//	*WKTNestedPool_ChoiceDur
	Choice        isWKTNestedPool_Choice `protobuf_oneof:"choice"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WKTNestedPool) Reset() {
	*x = WKTNestedPool{}
	mi := &file_pool_wkt_pool_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WKTNestedPool) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WKTNestedPool) ProtoMessage() {}

func (x *WKTNestedPool) ProtoReflect() protoreflect.Message {
	mi := &file_pool_wkt_pool_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WKTNestedPool.ProtoReflect.Descriptor instead.
func (*WKTNestedPool) Descriptor() ([]byte, []int) {
	return file_pool_wkt_pool_proto_rawDescGZIP(), []int{0}
}

func (x *WKTNestedPool) GetTs() *timestamppb.Timestamp {
	if x != nil {
		return x.Ts
	}
	return nil
}

func (x *WKTNestedPool) GetSt() *structpb.Struct {
	if x != nil {
		return x.St
	}
	return nil
}

func (x *WKTNestedPool) GetTss() []*timestamppb.Timestamp {
	if x != nil {
		return x.Tss
	}
	return nil
}

func (x *WKTNestedPool) GetSts() []*structpb.Struct {
	if x != nil {
		return x.Sts
	}
	return nil
}

func (x *WKTNestedPool) GetChoice() isWKTNestedPool_Choice {
	if x != nil {
		return x.Choice
	}
	return nil
}

func (x *WKTNestedPool) GetChoiceTs() *timestamppb.Timestamp {
	if x != nil {
		if x, ok := x.Choice.(*WKTNestedPool_ChoiceTs); ok {
			return x.ChoiceTs
		}
	}
	return nil
}

func (x *WKTNestedPool) GetChoiceDur() *durationpb.Duration {
	if x != nil {
		if x, ok := x.Choice.(*WKTNestedPool_ChoiceDur); ok {
			return x.ChoiceDur
		}
	}
	return nil
}

type isWKTNestedPool_Choice interface {
	isWKTNestedPool_Choice()
}

type WKTNestedPool_ChoiceTs struct {
	ChoiceTs *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=choice_ts,json=choiceTs,proto3,oneof"`
}

type WKTNestedPool_ChoiceDur struct {
	ChoiceDur *durationpb.Duration `protobuf:"bytes,6,opt,name=choice_dur,json=choiceDur,proto3,oneof"`
}

func (*WKTNestedPool_ChoiceTs) isWKTNestedPool_Choice() {}

func (*WKTNestedPool_ChoiceDur) isWKTNestedPool_Choice() {}

var File_pool_wkt_pool_proto protoreflect.FileDescriptor

const file_pool_wkt_pool_proto_rawDesc = "" +
	"\n" +
	"\x13pool/wkt_pool.proto\x1a3github.com/planetscale/vtprotobuf/vtproto/ext.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1egoogle/protobuf/duration.proto\x1a\x1cgoogle/protobuf/struct.proto\"\xc4\x02\n" +
	"\rWKTNestedPool\x12*\n" +
	"\x02ts\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\x02ts\x12'\n" +
	"\x02st\x18\x02 \x01(\v2\x17.google.protobuf.StructR\x02st\x12,\n" +
	"\x03tss\x18\x03 \x03(\v2\x1a.google.protobuf.TimestampR\x03tss\x12)\n" +
	"\x03sts\x18\x04 \x03(\v2\x17.google.protobuf.StructR\x03sts\x129\n" +
	"\tchoice_ts\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampH\x00R\bchoiceTs\x12:\n" +
	"\n" +
	"choice_dur\x18\x06 \x01(\v2\x19.google.protobuf.DurationH\x00R\tchoiceDur:\x04\xa8\xa6\x1f\x01B\b\n" +
	"\x06choiceB\x10Z\x0etestproto/poolb\x06proto3"

var (
	file_pool_wkt_pool_proto_rawDescOnce sync.Once
	file_pool_wkt_pool_proto_rawDescData []byte
)

func file_pool_wkt_pool_proto_rawDescGZIP() []byte {
	file_pool_wkt_pool_proto_rawDescOnce.Do(func() {
		file_pool_wkt_pool_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pool_wkt_pool_proto_rawDesc), len(file_pool_wkt_pool_proto_rawDesc)))
	})
	return file_pool_wkt_pool_proto_rawDescData
}

var file_pool_wkt_pool_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_pool_wkt_pool_proto_goTypes = []any{
	(*WKTNestedPool)(nil),         // 0: WKTNestedPool
	(*timestamppb.Timestamp)(nil), // 1: google.protobuf.Timestamp
	(*structpb.Struct)(nil),       // 2: google.protobuf.Struct
	(*durationpb.Duration)(nil),   // 3: google.protobuf.Duration
}
var file_pool_wkt_pool_proto_depIdxs = []int32{
	1, // 0: WKTNestedPool.ts:type_name -> google.protobuf.Timestamp
	2, // 1: WKTNestedPool.st:type_name -> google.protobuf.Struct
	1, // 2: WKTNestedPool.tss:type_name -> google.protobuf.Timestamp
	2, // 3: WKTNestedPool.sts:type_name -> google.protobuf.Struct
	1, // 4: WKTNestedPool.choice_ts:type_name -> google.protobuf.Timestamp
	3, // 5: WKTNestedPool.choice_dur:type_name -> google.protobuf.Duration
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_pool_wkt_pool_proto_init() }
func file_pool_wkt_pool_proto_init() {
	if File_pool_wkt_pool_proto != nil {
		return
	}
	file_pool_wkt_pool_proto_msgTypes[0].OneofWrappers = []any{
		(*WKTNestedPool_ChoiceTs)(nil),
		(*WKTNestedPool_ChoiceDur)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pool_wkt_pool_proto_rawDesc), len(file_pool_wkt_pool_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pool_wkt_pool_proto_goTypes,
		DependencyIndexes: file_pool_wkt_pool_proto_depIdxs,
		MessageInfos:      file_pool_wkt_pool_proto_msgTypes,
	}.Build()
	File_pool_wkt_pool_proto = out.File
	file_pool_wkt_pool_proto_goTypes = nil
	file_pool_wkt_pool_proto_depIdxs = nil
}
